config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get "/signup", to: 'users#new'
  post "/signup", to: 'users#create'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :accout_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :user_files, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_files, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 100, minimum: 3}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true,
                       length: { minimum: 6 },
                       allow_nil: true
  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_token.blank?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/user_file.rb
class UserFile < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :file_name, presence: true, length: { maximum: 11 }
  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    render html: "◈ ◐ ◑ ✖ ∞ « » ‹ › ✿ ☺ ☻ ☹ ☼ ☂ ☃ ⌇ ⚛ ⌨ ✆ ☎  ⌘ ⌥ ⇧ ↩ ✞ ✡ ☭ ← → ↑ ↓ ➫ ⬇ ⬆ ☜ ☞ ☝ ☟ ✍ ✎ ✌ ☮ ✔ ★ ☆ ♺ ⚑ ⚐ ✉ ✄ ⌲ ✈ ♦ ♣ ♠ ♥ ❤ ♡ ♪ ♩ ♫ ♬ ♯ ♀ ♂ ⚥ ⚢ ⚣ § ¶ ¡ ¿ ‽ ⁂ ※ ± × ~ ≈ ÷ ≠ π † ‡ ¥ € $ ¢ £ ß © ® @ ™ ° ‰ … · • ●"
  end


  private
    def loggedin_user
      unless loggedin?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_path
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login user
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render "new"
    end
  end

  def destroy
    logout if loggedin?
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

@@count = 0

  def home
    @@count += 1
    if loggedin?
      @user_file = current_user.user_files.build
      @file_listing = current_user.user_files.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController
  before_action :loggedin_user, only: [:create, :destroy]

  def create
    @user_file = current_user.user_files.build(user_file_params)
    if @user_file.save
      flash[:success] = "File generated"
      redirect_to root_path
    else
      @file_listing = []
      render "static_pages/home"
    end
  end

  def destroy
  end

  private

    def user_file_params
      params.require(:user_file).permit(:content)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :loggedin_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:delete]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @user_files = @user.user_files.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User removed"
    redirect_to users_path
  end

  def feed
    UserFile.where("user_id = ?", id)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title_helper(page_title = "")
    if page_title.empty?
      ":: RailsDucK ::"
    else
      ":: " + page_title + " ::"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        login user
        @current_user = user
      end
    end
  end

  def loggedin?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default )
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    grav_id = Digest::MD5::hexdigest(user.email.downcase)
    grav_url = "https://secure.gravatar.com/avatar/#{grav_id}?s=#{size}"
    image_tag(grav_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>(c) PuZZleDucK 2016 GPL3</p>
    <p>Page viewed at: <%= Time.now %></p>
  </small>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to about_path, about_path %></li>
      <li><%= link_to help_path, help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
<title><%= title_helper(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<nav>
  <%= link_to "FSM", root_path, id: "logo" %>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Help", help_path %></li>
    <% if loggedin? %>
      <li><%= link_to "Members", users_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> My Account <b class="carret"></b> </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Login", login_path %></li>
    <% end %>
  </ul>
</nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body>

  <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert-danger">
      submission contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |err| %>
        <li><%= err %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_file_listing.erb
<% if @file_listing.any? %>
  <ol class="file_listing">
    <%= render @file_listing %>
  </ol>
  <%= will_paginate @file_listing %>
<% end %>

app/views/shared/_user_file_form.erb
<%= form_for(@user_file) do |form| %>
  <%= render "shared/error_messages", object: form.object %>
  <div class="field">
    <%= form.text_field :file_name, placeholder: "file.txt" %>
  </div>
  <div class="field">
    <%= form.text_area :content, placeholder: "hello worlds" %>
  </div>
<% end %>

app/views/shared/_user_info.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.user_files.count, "file") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>


<h1>About Us</h1>
<p>Find us on the third Thursday of the month at Electron Workshop</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>How can we help you today?</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Welcome to Free Software Melbourne</h1>
</div>


<%= link_to image_tag("FSM_logo.png", alt: "FSM Home", width: "50px"), root_path %>


<p>You are the %= @@count % viewer :D</p>

<% if loggedin? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="user_file_form">
        <%= render "shared/user_file_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>File Listing</h3>
      <%= render "shared/file_listing"%>
    </div>
  </div>
<% else %>
  <%= link_to "Join Us", signup_path, class: "btn btn-lg btn-primary" %>
<% end %>

app/views/user_files/_user_file.html.erb
<li id="user_file-<%= user_file.id%>">
  <%= link_to gravatar_for(user_file.user, size: 50), user_file.user %>
  <span class="user"><%= link_to user_file.user.name, user_file.user %></span>
  <span class="timestamp"><%= time_ago_in_words(user_file.created_at) %></span>
  <span class="filename"><%= user_file.file_name %></span>
  <span class="contents"><%= user_file.content %></span>

</li>

app/views/users/_basic_form.html.erb
  <%= form_for(@user) do |form| %>
    <%= render "shared/error_messages", object: form.object %>
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>

    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>

    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>

    <%= form.label :password_confirmation, "Confirm password" %>
    <%= form.password_field :password_confirmation, class: "form-control" %>

    <%= form.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 20 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit FSM profile') %>
<% provide(:button_text, 'Save profile changes') %>
<h1>Update profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "basic_form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>
<p>The mailing list is another option</p>

app/views/users/index.html.erb
<% provide(:title, 'Edit FSM profile') %>
<h1>FSM Member List</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Join FSM') %>
<h1>Join FSM</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "basic_form" %>
  </div>
</div>
<p>The mailing list is another option</p>

app/views/users/show.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h2><%= @user.name %> <%= gravatar_for @user %></h2>
      <p>Signed up: <%= @user.created_at %></p>
      <p>Last updated profile: <%= @user.updated_at %></p>
      <p>Contact: <%= @user.email %></p>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.user_files.any? %>
      <h3>Files (<%= @user.user_files.count %>)</h3>
      <ol class="user_files">
        <%= render @user_files %>
      </ol>
      <%= will_paginate @user_files %>
    <% end %>
  </div>
</div>